services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flash_fathom_frontend
    env_file:
      - .env
    networks:
      - flash_fathom
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14
    container_name: supabase_postgres
    env_file:
      - .env
    networks:
      - flash_fathom
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  flash_fathom:
    driver: bridge

volumes:
  postgres_data:
