name: Add contributors
on:
  push:
    branches:
      - main

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BobAnkh/add-contributors@v2  # Use the latest stable version
        with:
          CONTRIBUTOR: "## Contributors"
          COLUMN_PER_ROW: "6"
          ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}  # Ensure this matches the secret name in GitHub
          IMG_WIDTH: "100"
          FONT_SIZE: "14"
          PATH: "/README.md"
          COMMIT_MESSAGE: "docs(README): update contributors"
          AVATAR_SHAPE: "circle"
